### ISSUE TITLE
First Issue! Compiling & Flashing on macOS success but boot fail

### ISSUE THREAD

**Issue by DarthHTTP** [supergreenlab/SuperGreenOS#1] opened 2020-05-04 11:38 UTC
Hi

i'm trying to compile SuperGreenOS on macos, i have successfully installed idf ecosystem, i have a ESP32-CAM around to test, i can flash the hello-world from idf.
I'm NOT super experienced with idf, i'm used to platformio, so please keep that in mind :)

a. i've replaced everywhere i could find hardcoded references to serial device **(/dev/ttyUSB1**) with my serial device;

**b. snprintf**

on `make -j4` i get:

```
.../esp/SuperGreenOS/main/core/httpd/httpd.c: In function 'get_ip_handler':
.../esp/SuperGreenOS/main/core/httpd/httpd.c:248:42: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
   snprintf(ip, sizeof(ip)-1, "%d.%d.%d.%d", iphex[0], iphex[1], iphex[2], iphex[3]);
                                          ^
.../esp/SuperGreenOS/main/core/httpd/httpd.c:248:3: note: 'snprintf' output between 8 and 16 bytes into a destination of size 15
   snprintf(ip, sizeof(ip)-1, "%d.%d.%d.%d", iphex[0], iphex[1], iphex[2], iphex[3]);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC build/lwip/lwip/src/core/def.o
cc1: some warnings being treated as errors
make[1]: *** [core/httpd/httpd.o] Error 1
make: *** [component-main-build] Error 2
```

which i've tried to solve by 1. unsuccessfully trying to disable -Werror; 2. added more space in the buffer; `**char ip[17] = {0};**`
error solved;

**c. mqtt_event_handler ()**

```
../esp/SuperGreenOS/main/core/mqtt/mqtt.c: In function 'mqtt_event_handler':
../esp/SuperGreenOS/main/core/mqtt/mqtt.c:45:3: error: enumeration value 'MQTT_EVENT_ANY' not handled in switch [-Werror=switch]
   switch (event->event_id) {
   ^~~~~~
cc1: some warnings being treated as errors
make[1]: *** [core/mqtt/mqtt.o] Error 1
make: *** [component-main-build] Error 2
```

which i've solved by adding it in the switch statement;
```
    case MQTT_EVENT_ANY:
      ESP_LOGI(SGO_LOG_EVENT, "MQTT_EVENT_ANY");
      break;
```

**At this point - make -j4 reports building success:**

```
Generating esp32.project.ld
LD build/firmware.elf
esptool.py v3.0-dev
```

d. make -j4 flash is successful, ./write_spiffs.sh is successful, but **esp32 goes into a reboot cycle,**

error is
```

I (638) EVENT: @MAIN Welcome to SuperGreenOS version=SuperGreenDriver

I (688) EVENT: @REBOOT N_SHORT_REBOOTS=4
E (718) EVENT: @WIFI MDNS Init failed: 259

Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x40001277  PS      : 0x00060b30  A0      : 0x800d6b10  A1      : 0x3ffbe900
A2      : 0x000002e2  A3      : 0x3f4044f3  A4      : 0x3f412e14  A5      : 0x3ffbea30
A6      : 0x3ffbea10  A7      : 0x0000000c  A8      : 0x800f3de5  A9      : 0x3ffbe840
A10     : 0x0000000d  A11     : 0xffffffff  A12     : 0x00000000  A13     : 0x3f412e14
A14     : 0x00000001  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c
EXCVADDR: 0x000002e2  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffe

Backtrace:0x40001274:0x3ffbe900 0x400d6b0d:0x3ffbe910 0x4017a6fa:0x3ffbe9d0 0x4008767d:0x3ffbea00 0x40119a81:0x3ffbea50 0x4013527f:0x3ffbeac0 0x4013094b:0x3ffbeb00 0x40118104:0x3ffbeb20 0x40118216:0x3ffbeb40 0x40117079:0x3ffbeb60 0x400df39d:0x3ffbeb80 0x400d449c:0x3ffbec70 0x400d2dbc:0x3ffbec90
0x400d6b0d: mqtt_logging_vprintf at .../esp/SuperGreenOS/main/core/mqtt/mqtt.c:149

0x4017a6fa: esp_log_writev at .../esp/esp-idf/components/log/log.c:189

0x4008767d: esp_log_write at .../esp/esp-idf/components/log/log.c:199

0x40119a81: wifi_log at ??:?

0x4013527f: pp_create_task at ??:?

0x4013094b: ic_create_wifi_task at ??:?

0x40118104: wifi_init_in_caller_task at ??:?

0x40118216: esp_wifi_init_internal at ??:?

0x40117079: esp_wifi_init at .../esp/esp-idf/components/esp_wifi/src/wifi_init.c:146

0x400df39d: init_wifi at .../esp/SuperGreenOS/main/core/wifi/wifi.c:70

0x400d449c: app_main at .../esp/SuperGreenOS/main/core/app_main.c:48

0x400d2dbc: main_task at .../esp/esp-idf/components/esp32/cpu_start.c:580
```

Anyone can help ?
thx a lot!

**Comment by vitaminwater** [comment] 2020-05-04 13:18
Hi man, thanks for taking the time to try this:)

What version of esp-idf are you using?
I'm using release/v3.3, that could be the issue, I haven't tried using v4 yet.

**Comment by DarthHTTP** [comment] 2020-05-04 13:23
i've followed what was suggested in the Readme:
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/

so i have master branch of https://github.com/espressif/esp-idf.git
but i will switch to the 3.3 and try and come back
thanks!

**Comment by analogmonster** [comment] 2020-06-28 22:58
I can't help with closing this issue, but I was having similar issues.  Applying the above 2 fixes helped, I got make -j4 success.  But failed at make -j4 flash monitor (can't rememver the cause but I may try again later).  I tried switching esp-idf, but I am having issues switching over.  I think it is python 2.7 vs 3 related but to be honest it is beyond me.  @DarthHTTP any progress on you switching to 3.3 or are you in a similar position?

**Comment by DarthHTTP** [comment] 2020-07-01 09:30
@analogmonster indeed we should have marked resolved this issue, since then i've succeeded with the help of @vitaminwater getting all the toolbox running & contributing a bit to the codebase, i've added some README instructions, here already, 
checkout subheading: _**Up-2-date dev environment setup 06/2020**_

if you'd like help please join SGL's discord, we'll take it from there.

**Closed as completed** 2020-07-01 16:12 UTC
